services:
  mysql_cadastramento:
    image: mysql:5.7
    container_name: mysql_cadastramento
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: banco_cadastramento
    volumes:
    - ./ServicoCadastramento/banco_cadastramento.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  mysql_pagamentos:
    image: mysql:5.7
    container_name: mysql_pagamentos
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: banco_pagamentos
    volumes:
    - ./ServicoPagamentos/banco_pagamentos.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  servicocadastramento:
    build: ./ServicoCadastramento
    container_name: servicocadastramento
    ports:
      - '3000:3000'
    depends_on:
      - mysql_cadastramento
      - rabbitmq
    networks:
      - app-network

  servicopagamentos:
    build: ./ServicoPagamentos
    container_name: servicopagamentos
    ports:
      - '4000:4000'
    depends_on:
      - mysql_pagamentos
      - rabbitmq
    networks:
      - app-network

  servicoassinaturasvalidas:
    build: ./ServicoAssinaturasValidas
    container_name: servicoassinaturasvalidas
    ports:
      - '5000:5000'
    depends_on:
      - servicocadastramento
      - rabbitmq
    networks:
      - app-network

networks:
  app-network: